name: Trigger Docker Image Build

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
  
    - name: Deploy Docker Pipeline
      id: deploy_docker_pipeline
      if: >-
        always() &&
        !cancelled()
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/NHSDigital/nhs-notify-docker-images/actions/workflows/docker.yml/dispatches \
        -d '{
        "ref": "'"${{ github.ref_name }}"'"
        }'
